# kube-prometheus-stack Helm values
# Optimized for cost-effective single-node EKS cluster

# Prometheus configuration
prometheus:
  prometheusSpec:
    # Resource limits for cost optimization
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

    # Storage configuration
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

    # Retention period (reduced to 2d due to disk space constraints)
    retention: 2d

    # Service monitors to discover
    serviceMonitorSelectorNilUsesHelmValues: false

# Grafana configuration
grafana:
  enabled: true

  # Admin credentials (change in production!)
  adminPassword: admin

  # Resource limits
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

  # Persistence for dashboards
  persistence:
    enabled: true
    size: 5Gi

  # Service configuration - LoadBalancer for external access
  service:
    type: LoadBalancer
    port: 80

  # Pre-installed dashboards
  defaultDashboardsEnabled: true

  # Datasources - use default configuration from chart
  # The chart automatically configures Prometheus as datasource

# AlertManager configuration (minimal for cost savings)
alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi

# Node exporter - monitors node metrics
prometheus-node-exporter:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Kube-state-metrics - monitors Kubernetes objects
kube-state-metrics:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

# Disable components not needed for basic monitoring
kubeApiServer:
  enabled: true

kubelet:
  enabled: true

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kubeEtcd:
  enabled: false
